- name: Fix mounts and docker services on boot
  block:
    - name: Copy boot-fix script
      template:
        src: boot-fix.sh
        dest: /usr/local/bin/boot-fix.sh
        mode: 0755

    - name: Copy boot-fix systemd service
      copy:
        src: boot-fix.service
        dest: /etc/systemd/system/boot-fix.service
        mode: 0644
      register: boot_fix_service

    - name: Enable boot-fix service
      systemd:
        name: boot-fix.service
        enabled: yes
        daemon_reload: "{{ boot_fix_service is changed }}"
  tags: boot-fix
